--- 
title: "The OBIS manual"
site: "bookdown::bookdown_site"
output:
  bookdown::gitbook:
    split_by: rmd
documentclass: book
biblio-style: apalike
link-citations: yes
editor_options: 
  chunk_output_type: console
---

# Introduction

This manual provides an overview on how to contribute data to OBIS and how to acess data from OBIS. It provides guidelines for OBIS nodes and data providers on the OBIS standards and data management best practices to ensure that data published via OBIS are of high quality and follows internationally recognised standards. It also provides guidelines for data users on how to access, process and visualize data from OBIS.

The OBIS node manual is a dynamic document and is revised on a regular basis. Suggestions for additions and changes to this document are welcome and can be sent to the OBIS Capacity Development Task Team by email to [training@obis.org](mailto:training@iobis.org) or added as issues at <https://github.com/iobis/manual/issues>. 

## Guidelines on the sharing and use of data in OBIS

It is important that our data providers as well as all the data users are aware and agree on the [OBIS guidelines on the sharing and use of data in OBIS](policy), which was adoped at the [4th OBIS Steering Group](https://obis.org/about/sg-obis-4).

## Acknowledgements

This manual received contributions from: [Leen Vandepitte](https://www.oceanexpert.net/expert/12313), [Mary Kennedy](https://www.oceanexpert.net/expert/13557), [Philip Goldstein](https://www.oceanexpert.net/expert/18051), [Pieter Provoost](https://www.oceanexpert.net/expert/26192), [Samuel Bosch](https://www.oceanexpert.net/expert/26577) and [Ward Appeltans](https://www.oceanexpert.net/expert/11770). 
