---
title: "Tutorials"
sidebar: tutorials
toc: false
title-block-banner: "#445599"
listing:
  id: tutorials-listings
  contents: 
    - tutorials
    #- tutorials.yml
  sort: "date desc"
  max-items: 4
---

```{=html}
<style>
.quarto-title-block .quarto-title-banner {
    background: #2A7B9B;
    background-image:
        url("/images/blue-square-bg.svg"),
        linear-gradient(90deg, #469cd6 0%, #0c29ad 100%);
    background-repeat: no-repeat, no-repeat;
    background-size: 50% auto, cover;
    background-position: right, center;
    opacity: 0;
    animation: fadeInBanner 0.2s ease-in forwards;
}
@keyframes fadeInBanner {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

.sidebar-item .menu-text {
    font-size: 20px;
    font-weight: bold;
}

#title-block-header h1 {
    color: white;
    font-size: 50px;
}
</style>
```

Explore how to use OBIS data on a more efficient way with tutorials created by OBIS and partners. You can also contribute with tutorials following the guidelines available at our [repository](https://github.com/iobis/resources).

Don’t know where to start? We suggest reading the OBIS manual where you will find the most complete guide about how OBIS works and the different types of data available. Video tutorial playlists are also available from the YouTube logo [OBIS YouTube channel](https://www.youtube.com/@oceanbiodiversityinformati6931/playlists). Some highlights from our How-To videos include:

* How to [construct eventIDs](https://www.youtube.com/watch?v=Upt6LPJ0Bn8&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=2&t=6s)
* How to create and format the [Event](https://www.youtube.com/watch?v=jyy6QO_p7v8&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=4), [Occurrence](https://www.youtube.com/watch?v=G_AmAmS7ILc&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=5), and [eMoF](https://www.youtube.com/watch?v=EjM0HRrF1B4&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=6) tables
* How to access data from OBIS using the [Mapper](https://www.youtube.com/watch?v=9PSPEtqgjUI&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=11&t=1s) or [R](https://www.youtube.com/watch?v=8Ep4fGICQWU&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=12)
* How to [publish data to OBIS using the IPT](https://www.youtube.com/watch?v=i2P8mjo128o&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=8)
* How to [publish an OBIS dataset to GBIF](https://www.youtube.com/watch?v=HciufRG9hiI&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=10)
* How to use the [OBIS MapTool](https://www.youtube.com/watch?v=XM23WEvE364&list=PLlgUwSvpCFS4TS7ZN0fhByj_3EBZ5lXbF&index=14)
* A playlist dedicated to helping you [find and select controlled vocabulary](https://www.youtube.com/playlist?list=PLlgUwSvpCFS4hADB7Slf44V1KJauEU6Ul)

<br>

## Recent tutorials

::: {#tutorials-listings}
:::
