# Data publication and sharing

Once you have finished [formatting your data](formatting.html) and have conducted some basic [quality control procedures](data_qc.html) on it, you are ready to publish your dataset to OBIS. Note that OBIS nodes can accept any data files from its data sources or data providers, and they publish these data on their respective OBIS node Integrated Publishing Toolkit (IPT). Data from [node IPTs](https://ipt.iobis.org/) are then harvested by central OBIS to become [accessible via the global database](access.html#full-exports). The Integrated Publishing Toolkit (IPT) is developed and maintained by the Global Biodiversity Information Facility (GBIF). While GBIF maintains an [IPT manual](https://www.gbif.org/ipt), we outline specific OBIS instructions here.

Some nodes require the **manager themself to upload data**. This means after you have formatted your data for OBIS and have done some [basic quality control steps](data_qc.html), you simply pass this file on to the appropriate node manager. They will communicate with you any issues during the publication process.

Sometimes a node manager will request the **data provider to upload their own dataset** to the IPT. If you the data provider are required to upload your data then there are a number of steps you will take to upload your data. A reminder that all data formatting and quality control steps should be completed before uploading your dataset. Once uploaded, the node manager will check your upload before publishing the dataset.

There are a few steps involved to publish a dataset, whether you are the provider or the node manager. You must:

1. Identify the correct [IPT](https://ipt.iobis.org/) for your [OBIS node](https://obis.org/contact/) (you may have to contact your node manager to confirm IPT)
2. Login to the IPT, or have the node manager create an account for you if you do not have one, so you can upload your dataset(s)
3. Map each of your fields to Darwin Core terms. This should be relatively straight forward if you have done this already during [data formatting](formatting.html)
4. [Fill all relevant metadata](eml.html) to help users understand and cite your dataset
5. Publish and make your data public

Details for each of these steps are outlined on the subsequent pages. We will start with an overview of which Creative Commons license should be used, and then move on to using the IPT to publish data.

## Licenses

OBIS nodes must make the necessary agreements with the original data providers so that data can be made available to OBIS under one of the following Creative Commons licenses (in order of preference):

* [CC0](https://creativecommons.org/publicdomain/zero/1.0/) -  data may be used without restrictions
* [CC-BY](https://creativecommons.org/licenses/by/4.0/) - data are available for any use if proper attribution and credit is given
* [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) - data may be used for any non-commercial use as long as proper attribution/credit is given

You may need to consult with your organization if there are any copyright concerns. For more information on the different Creative commons license types see [About the licenses](https://creativecommons.org/licenses/).
